llCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
Rails:
  Enabled: true
CaseIndentation:
  # Valid values are: case, end
  EnforcedStyle: case
  IndentOneStep: true
Bundler/OrderedGems:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 7
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 8
Metrics/BlockLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/Lambda:
  Enabled: false
StringLiterals:
  EnforcedStyle: single_quotes
Style/RaiseArgs:
  EnforcedStyle: compact
Style/RedundantSelf:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/TrailingBlankLines:
  Enabled: false
