---
- name: Install common pkgs
  become: yes
  yum: pkg={{item}} state=present
  with_items:
    - aws-cli
    - git

- name: place git-completion.sh
  copy: src=git-completion.sh dest=~/.git-completion.sh mode=0644

- name: place bashrc
  copy: src=bashrc dest=~/.bashrc mode=0644
